apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  ports:
  - port: 5433
    targetPort: 5433
  selector:
    app: postgres
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: trungnq72-config-map
data:
  DB_NAME: trungnq72-database
  DB_USER: trungnq72-user
  DB_HOST: postgres-service
  DB_PORT: "5433"
---
apiVersion: v1
kind: Secret
metadata:
  name: trungnq72-secret
type: Opaque
data:
  DB_PASSWORD: dHJ1bmducTcyLXByaXZhdGUta2V5