apiVersion: v1
kind: Service
metadata:
  name: trungnq72-coworking
spec:
  type: LoadBalancer
  selector:
    service: trungnq72-coworking
  ports:
  - name: "5153"
    protocol: TCP
    port: 5153
    targetPort: 5153
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trungnq72-coworking
  labels:
    name: trungnq72-coworking
spec:
  replicas: 1
  selector:
    matchLabels:
      service: trungnq72-coworking
  template:
    metadata:
      labels:
        service: trungnq72-coworking
    spec:
      containers:
      - name: trungnq72-coworking
        image: <DOCKER_IMAGE_URI_FROM_ECR>
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /health_check
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            path: "/readiness_check"
            port: 5153
          initialDelaySeconds: 5
          timeoutSeconds: 5
        envFrom:
        - configMapRef:
            name: trungnq72-config-map
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trungnq72-secret
              key: DB_PASSWORD
      restartPolicy: Always