apiVersion: apps/v1
kind: Deployment
metadata:
  name: trungnq72-postgresql
spec:
  selector:
    matchLabels:
      app: trungnq72-postgresql
  template:
    metadata:
      labels:
        app: trungnq72-postgresql
    spec:
      containers:
      - name: trungnq72-postgresql
        image: postgres:latest
        env:
        - name: POSTGRES_DB
          value: trungnq72-database
        - name: POSTGRES_USER
          value: trungnq72-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: trungnq72-secret
              key: DB_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: trungnq72-postgresql-storage
      volumes:
      - name: trungnq72-postgresql-storage
        persistentVolumeClaim:
          claimName: trungnq72-postgresql-pvc