apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: trungnq72-postgresql-pvc
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi